### ISSUE TITLE
Copiar ou remover o .env do controle de versão (git)

### ISSUE THREAD

**Issue by huogerac** [evolutio/djavue3#116]
- Ter o .env comitado pode atrapalhar alguns deploys como no Heroku. Se fazemos deploy via docker é tranquilo colocar no .dockerignore, mas alguns cenários o .env pode atrabalhar dependendoo do ambiente que o projeto roda.

## Solução

- Renomear o .env para .env.example e fazer commit
- Adicionar o .env no .gitignore e fazer o hooks da criação do projeto copiar o .env.sample para .env assim o projeto já nasce com um e ele não será adicionado nos commits. Ou seja, é muito chato tentar rodar o projeto e tomar erros pq está faltando variáveis

**Comment by niltonpimentel02** [comment]
@huogerac hello my friend! can i work on this? 😎
