### ISSUE TITLE
Adicionar na documentação como contribuir no projeto

### ISSUE THREAD

**Issue by huogerac** [evolutio/djavue3#121]
Basicamente é fazer um fork atualizando este arquivo aqui:
https://github.com/evolutio/djavue3/blob/main/docs/11-contribuindo.md

Conteúdo:
O processo para contribuir é :
- Fork do projeto para sua conta
- Clonar o proteto para um pasta na sua máquina
- Criar uma branch
- Alterar os arquivos necessários
- Fazer commit
- Fazer git push da branch da solução
- Fazer PR do projeto da conta do usuário para o repositório da evolutio/djavue3

Como testar minhas alterações?
Uma forma de testar localmente as alterações é gerar um projeto Djavue com o comando `cookiecutter gh:evolutio/djavue3`, e uma vez na pasta do novo projeto gerado com djavue, fazer um commit 'inicial'.
Assim gerar as alterações, seja na raiz ou na pasta frontend e assim gerar um ou mais commits com as alterações. Desta forma é possível saber a diferença (git diff) entre a nova versão e a versão inciais. Desta forma saberemos todos os arquivos necessários no repositório do Djaveu que precisam ser alterados. Note que todos arquivos do projeto gerado estão na pasta `{{cookiecutter.project_slug}}` 

Uma teste interessante antes de fazer push da branch da sua versão, é testá-la localmente. Para isto pasta utilizar o comando: `cookiecutter \homeuser\workspace\djavue3` ao invés de `cookiecutter https://github.com/evolutio/djavue3` .
Ou seja, podemos criar um novo projeto contra o nosso repositório clonado localmente ao invés do repositório do djavue. Esta é uma forma interessante de testar nossas alterações.

Outra dica é gerar vários projetos testando com e sem poetry, com e sim django ninja e assim por diante. Testar todas as possibilidades e garantir que todas as versões estão funcionando

**Comment by Gabriels999** [comment]
Sobre esse bloco aqui:

Como testar minhas alterações?
Uma forma de testar localmente as alterações é gerar um projeto Djavue com o comando cookiecutter gh:evolutio/djavue3, e uma vez na pasta do novo projeto gerado com djavue, fazer um commit 'inicial'.
Assim gerar as alterações, seja na raiz ou na pasta frontend e assim gerar um ou mais commits com as alterações. Desta forma é possível saber a diferença (git diff) entre a nova versão e a versão inciais. Desta forma saberemos todos os arquivos necessários no repositório do Djaveu que precisam ser alterados. Note que todos arquivos do projeto gerado estão na pasta {{cookiecutter.project_slug}}

Acho que eu não entendi muito bem a ordem da proposta. Essa abordagem seria para identificar o que alterar no código do djavue a partir de um projeto criado pelo formato atual ?
Poderia explicar melhor ?
