### ISSUE TITLE
Usar o Csv do python decouple no settings do Django.

### ISSUE THREAD

**Issue by HenriqueCCdA** [evolutio/djavue3#34]
Existe uma classe `Csv()` que podeira ser usada aqui:

https://github.com/evolutio/djavue3/blob/4cdb28faede5dfa782477b97086413d6b9d07fbf/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/settings.py#L35

O código atual:

```python
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="{{cookiecutter.deploy_domain}}",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
```

O código depois da modificação:

```python
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="{{cookiecutter.deploy_domain}}",
    cast=Csv(),
)
```

**Comment by huogerac** [comment]
Acabei de testar e tudo funcionou!

\o/
