### ISSUE TITLE
Gerar os arquivos do pip-tools a partir do pyproject.toml

### ISSUE THREAD

**Issue by huogerac** [evolutio/djavue3#65]
hoje cada versão do projeto (com django-ninja, django puro ou openapi) temos um arquivo .in específico.
Mas é possível remover estes arquivos duplicados e gerá-los automaticamente utilizando o pyproject.toml como fonte:

https://pip-tools.readthedocs.io/en/stable/#requirements-from-pyproject-toml

**Comment by joaoprocopio** [comment]
gostaria de pegarr essa issue
