### ISSUE TITLE
BUG: Falta do header content-type faz alguns backends não saber como converter os dados.

### ISSUE THREAD

**Issue by huogerac** [evolutio/djavue3#81]
Fazer as chamadas do frontend passar o header abaixo, ou seja, na pasta frontend/src/api, as chamadas tem que passar o header content-type. acredito que podemos colocar isto na inicialização do axios, desta forma todas chamadas vão passar esta informação.

Nota: vamos pensar que queremos usar este frontend para conectar em um backend nao django, como o fastapi. Vamos receber um erro sem este header. Entao como "Explicit is better than implicit" , é interessante termos este header nas chamadas ao backend!

Colocar de forma explícita o header:
```
  headers: {
    'Content-Type': 'application/json'
  }
```

**Comment by gbayres** [comment]
Has this already been fixed?
I've already found this header in the files

![axios](https://github.com/user-attachments/assets/c1df83d7-b787-4c09-b92b-caef8d224b60)

**Comment by huogerac** [comment]
I seems it is already solved! Thanks! and sorry, I do need to close some issues.
